version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    reviewers:
      - "wixplosives/Production-Engineers"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "09:00"
      timezone: "Israel"
