name: 'action-slack-message'
description: 'Sends slack messages'
author: 'Alex Shemshurenko'
inputs:
  status: 
    required: false
    description: 'failed or success'
    default: true
  text: 
    required: false
    description: 'free text'
    default: ''
  channel: 
    required: true
    description: 'channel to send message'
    default: 'core3-ci'
  slack_token: 
    required: true
    description: 'slack token'
    default: ''
runs:
  using: 'node12'
  main: 'dist/index.js'
