name: tests
on: [push, pull_request]
jobs:
  tests:
    name: node ${{ matrix.node-version }} / ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node-version: [14]
        os: [ubuntu-latest, windows-latest, macOS-latest]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
  ### below are just test cases ###
  send-file:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    steps:
      - name: Send file by name
        uses: 'wixplosives/action-slack-message@yarden/send-file-by-pattern'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          channel: 'testing-yarden-public'
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          file_name: README.md
          action_link: 'https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}'
      - name: Send files by pattern
        uses: 'wixplosives/action-slack-message@yarden/send-file-by-pattern'
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          channel: 'testing-yarden-public'
          slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
          file_pattern: git
          action_link: 'https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}'
