name: 'build-test'
on: push

jobs:
    build: # make sure build/ci work properly
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - run: |
                  npm install
            - run: |
                  npm run all
    notify-2-node-versions: # Send a Slack message
        runs-on: ubuntu-latest
        strategy:
            matrix:
                node-version: [14, 12]
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: Notify slack
              uses: 'wixplosives/action-slack-message@yarden/get-action-links'
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  text: 'failed text - optional'
                  status: ${{job.status}}
                  channel: 'testing-yarden-public'
                  slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
    notify:
        runs-on: ${{ matrix.os }}
        strategy:
            matrix:
                node-version: [14, 12]
                os: [ubuntu-latest, macos-latest, windows-latest]
        steps:
            - uses: actions/setup-node@v1
              with:
                  node-version: ${{ matrix.node }}
            - name: Notify slack
              uses: 'wixplosives/action-slack-message@yarden/get-action-links'
              env:
                  GITHUB_TOKEN: ${{ github.token }}
              with:
                  text: 'Some optional text above the attachment'
                  status: ${{job.status}}
                  channel: 'testing-yarden-public'
                  slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
